"""empty message

Revision ID: 33f3a6eb105d
Revises: 19f3a3143366
Create Date: 2025-11-27 07:46:54.949070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33f3a6eb105d'
down_revision: Union[str, Sequence[str], None] = '19f3a3143366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists', sa.Column('title', sa.String(length=255), nullable=False))
    op.drop_column('playlists', 'playlist_name')
    op.alter_column('songs', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('songs', 'song_link')
    op.alter_column('songs_playlists_association', 'song_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('songs_playlists_association', 'song_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.add_column('songs', sa.Column('song_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('songs', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('playlists', sa.Column('playlist_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('playlists', 'title')
    # ### end Alembic commands ###
