"""empty message

Revision ID: 6e50afcde576
Revises: fdac86f1ae7f
Create Date: 2025-11-17 03:49:31.511084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e50afcde576'
down_revision: Union[str, Sequence[str], None] = 'fdac86f1ae7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs_playlists_association', sa.Column('json_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs_playlists_association', 'json_meta')
    # ### end Alembic commands ###
