"""empty message

Revision ID: a2ce77784b87
Revises: 4add47b7420c
Create Date: 2025-12-15 15:59:03.473577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2ce77784b87'
down_revision: Union[str, Sequence[str], None] = '4add47b7420c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activation_toggle_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'activation_toggle_time')
    # ### end Alembic commands ###
