"""empty message

Revision ID: b2b7f619af54
Revises: 33f3a6eb105d
Create Date: 2025-11-28 11:04:40.753491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2b7f619af54'
down_revision: Union[str, Sequence[str], None] = '33f3a6eb105d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs_playlists_association', 'json_meta')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs_playlists_association', sa.Column('json_meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
